# -*- coding: utf-8 -*-
from docx.enum.text import WD_ALIGN_PARAGRAPH
from helpers import p, page_break


def add_title_page(doc):
    C = WD_ALIGN_PARAGRAPH.CENTER
    p(doc, "UNIVERSITY OF ENERGY AND NATURAL RESOURCES, SUNYANI", bold=True, align=C, size=16, space_after=4)
    p(doc, "SCHOOL OF SCIENCES", bold=True, align=C, size=13, space_after=4)
    p(doc, "DEPARTMENT OF COMPUTER SCIENCE AND INFORMATICS", bold=True, align=C, size=13, space_after=30)
    p(doc, "AN INTEGRATED EXAMINATION TIMETABLING AND", bold=True, align=C, size=15, space_after=2)
    p(doc, "INVIGILATOR VERIFICATION SYSTEM USING", bold=True, align=C, size=15, space_after=2)
    p(doc, "CONSTRAINT-BASED SCHEDULING AND VENUE-BOUND", bold=True, align=C, size=15, space_after=2)
    p(doc, "QR-CODE AUTHENTICATION", bold=True, align=C, size=15, space_after=36)
    p(doc, "BY", align=C, size=12, space_after=6)
    p(doc, "[STUDENT NAME]", bold=True, align=C, size=13, space_after=2)
    p(doc, "[INDEX NUMBER]", align=C, size=12, space_after=36)
    p(doc, "A project report submitted to the Department of Computer Science and Informatics, "
           "University of Energy and Natural Resources, in partial fulfilment of the requirements "
           "for the award of the degree of Bachelor of Science in Computer Science.", align=C, size=12, space_after=30)
    p(doc, "SUPERVISOR: [SUPERVISOR NAME]", bold=True, align=C, size=12, space_after=12)
    p(doc, "SEPTEMBER, 2026", bold=True, align=C, size=12)


def add_declaration(doc):
    page_break(doc)
    p(doc, "DECLARATION", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=14, space_after=18)
    p(doc, "I hereby declare that this project report is the result of my own original work carried out "
           "under supervision, and that no part of it has been presented for another degree in this "
           "university or elsewhere. All sources of information used have been duly acknowledged by "
           "means of references.")
    p(doc, "")
    p(doc, "Candidate's Signature: ......................................        Date: ........................", space_after=4)
    p(doc, "Name: [STUDENT NAME]", space_after=24)
    p(doc, "CERTIFICATION", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=14, space_after=18)
    p(doc, "I hereby certify that this project report was prepared by the above-named candidate under my "
           "supervision in accordance with the guidelines on project work laid down by the University of "
           "Energy and Natural Resources.")
    p(doc, "")
    p(doc, "Supervisor's Signature: ......................................        Date: ........................", space_after=4)
    p(doc, "Name: [SUPERVISOR NAME]")


def add_abstract(doc):
    page_break(doc)
    p(doc, "ABSTRACT", bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=14, space_after=18)
    p(doc, "Examination administration in many higher-education institutions remains a largely manual "
           "exercise: course lists are collected by electronic mail, examination timetables are constructed "
           "by hand in spreadsheets, and invigilator attendance is recorded on paper sign-in sheets that "
           "can be forged, signed remotely, or completed after the fact. This project designed, implemented "
           "and evaluated an integrated, web-based examination timetabling and invigilator verification "
           "system for the University of Energy and Natural Resources (UENR). The system digitises the "
           "complete examination lifecycle across six functional domains: academic structure management, "
           "structured course submission and approval, constraint-based examination timetable generation "
           "with venue allocation, automatic invigilator-to-venue assignment, QR-code-based physical "
           "presence verification, and real-time attendance monitoring. Timetables are generated by a "
           "greedy first-fit-decreasing heuristic with a three-pass constraint-relaxation strategy and up "
           "to twenty randomised retries, enforcing hard constraints on venue capacity and student-cohort "
           "clashes. Invigilators are assigned by a round-robin algorithm that prevents double-booking and "
           "same-department invigilation. Attendance is verified through venue-bound QR codes that encode "
           "the venue and examination session; a two-stage preview-then-confirm scan protocol validates the "
           "token format, the invigilator's assignment, the venue identity, duplicate attempts and a strict "
           "time window, persisting every outcome for forensic audit. A Socket.IO layer delivers real-time "
           "check-in and absence notifications to examination officers, supported by a background job that "
           "automatically marks missed scans as absent within five minutes. The system was implemented as a "
           "React 18 progressive web application over a Node.js/Express REST API with a PostgreSQL database "
           "accessed through Prisma ORM, and secured with JWT authentication, role-based access control, "
           "schema validation and immutable audit logging. Functional evaluation against the six research "
           "objectives confirmed clash-free timetables, conflict-free assignments, correct rejection of all "
           "fraudulent scan scenarios, and sub-five-minute absence detection. The work demonstrates that an "
           "integrated, venue-bound verification approach materially strengthens examination integrity "
           "without specialised hardware.", size=11)
    p(doc, "Keywords: examination timetabling, constraint-based scheduling, QR-code verification, "
           "invigilator attendance, role-based access control, real-time systems, progressive web application.",
      italic=True, size=11)
